### ISSUE TITLE
Change object-shorthand to `["error", "always"]`

### ISSUE THREAD

**Issue by hildjj** [peggyjs/peggyjs-eslint-config#1]
I disagree with the reasoning given at:

https://github.com/peggyjs/peggyjs-eslint-config/blob/260b56483833b25801a9712b5199b37fc5bf6e0c/index.js#L477

```js
    // Set not to require shorthands for properties because their syntax is
    // misleading. It conflates together a key name and a variable name, which
    // are the same only by coincidence and represent completely different
    // things with different reasons for change. Method shorthands are fine in
    // this respect (they only save typing a colon and the `function` keyword).
```

Idiomatic modern javascript has gotten over this difference, and have embraced the terse.

**Comment by hildjj** [comment]
@StoneCypher @mingun @phpnode opinions?

e.g. replace:

```js
check: {
      reportUndefinedRules,
      reportDuplicateRules,
      reportDuplicateLabels,
      reportInfiniteRecursion,
      reportInfiniteRepetition,
      reportIncorrectPlucking
    },
```

with:

```js
check: {
      reportUndefinedRules: reportUndefinedRules,
      reportDuplicateRules: reportDuplicateRules,
      reportDuplicateLabels: reportDuplicateLabels,
      reportInfiniteRecursion: reportInfiniteRecursion,
      reportInfiniteRepetition: reportInfiniteRepetition,
      reportIncorrectPlucking: reportIncorrectPlucking
    },
```

**Comment by Mingun** [comment]
OK from me, this is better.

**Comment by StoneCypher** [comment]
This should be the modern norm

```
export { foo, bar };
```

**Comment by StoneCypher** [comment]
wow that is a counterintuitive rule naming on eslint's part.  i read that to mean "the use of shorthand properties is always an error," which is the exact opposite of what it really means

as a general point, can we make what amount to formatting rules be warnings, rather than errors?  it's nice to just get told but still have your build go so you can learn the thing you wanted to learn, then fix it on the next way through

if not that's cool too

**Comment by hildjj** [comment]
I feel pretty strongly about linting.  What we probably ought to do is add it as a precondition to test, so you catch it locally.  It's pretty fast, so it shouldn't slow you down much.  There's an alternate approach in https://github.com/peggyjs/peggy/issues/42 that we could pursue as well.

**Comment by StoneCypher** [comment]
I don't mean to de-risk it.  This is actually an iconoclastic use of linters and similar tools on my part

In C++, `-wall -werror -wwtf -wohmygod -wwhatareyoudoing`

The difference, to me, between a warning and an error is "should it keep building while you're in the editor fixing it, or should it halt right now because everything downstream is trash"

Nothing goes in with an error, even

It's just a convenience.  If there's a formatting error, don't kill the build, because there might also be a test error, and that removes one cycle from the total build process.  Those are two distinct "you done screwed ups" I can get from the same build pass.

**Comment by hildjj** [comment]
If it were convenient to use a different set of rules for CI than command line, I'd be open to that.  I want lint errors to fail CI.

**Comment by StoneCypher** [comment]
I now have this CI-vs-local difference working, though it is currently blocked by #107
